### PR TITLE
Resolves #669

### LINKED ISSUE #669: Transform name -> branch name: be more careful
I got an error message running a transform:

`      Command failed: git push --force --no-verify --set-upstream origin atomist-internal/transform-change_deprecated_emptyIterator()_to_modern_one-20190201111921`

when we change the name to something branch-compatible, we need to remove parens and colons and etc etc.

Or, give me an error message about name format.

### PR DESCRIPTION
**Pull request by timothysparg**
Hi, 

I saw this open issue on the backlog and created a pull-request to resolve it. 
Could you provide some feedback on changes that I would need in order to get this merge in?

Additional info:
- the ruleset is based on the [git-check-ref-format man page](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html)
- I had to export the gitBranchCompatible function in order to test it, is there a better approach?

### CODE REVIEW

File: lib/api-helper/machine/handlerRegistrations.ts [hunk 1]
```diff
@@ -713,8 +713,42 @@ function toEditModeOrFactory<P>(ctr: CodeTransformRegistration<P>,
...
+ */
+export function gitBranchCompatible(name: string): string {
+    // handles spaces and .. ~ : ^ ? * [ @{
+    let branchName = name.replace(/\s+|(\.\.)+|~+|:+|\^+|\?+|\*+|\[+|(\@\{)+/g, "_");
+
+    // handles double slashes
+    branchName = branchName.replace(/(\/\/)+|(\\)+/g, "/");
+
+    // handles back slashes
+    branchName = branchName.replace(/\\+/g, "/");
```
Comment (ddgenome) [inline lib/api-helper/machine/handlerRegistrations.ts]: Wouldn't the previous replace take care of this? In other words, I think this replacement can be removed.

File: test/api-helper/machine/handlerRegistration.test.ts [hunk 2]
```diff
@@ -40,4 +40,58 @@ describe("handlerRegistration", () => {
 
     });
 
+    describe("gitBranchCompatible", () => {
+
+            it("remove spaces from branch name", async () => {
```
Comment (ddgenome) [inline test/api-helper/machine/handlerRegistration.test.ts]: Great tests. They do not need to be async, but I suppose it doesn't hurt.

**Comment by cdupuis** [comment]
Pull request auto merged by Atomist.

* 1 approved review by @ddgenome
* 1 successful check

[atomist:generated] [auto-merge:on-approve]

**Comment by ddgenome** [comment]
Sadly there does not seem to be a reasonable way of testing without exporting first.
